---
version: '2'
services:
  s3proxy:
    image: andrewgaul/s3proxy:latest
    container_name: s3proxy
    restart: always
    ports:
      - '8001:80'
    volumes: 
      - ./volumes/s3proxy:/data
    environment:
      S3PROXY_AUTHORIZATION: none
