version: '3.1'

services:
  postgres_keycloak:
    image: postgres
    container_name: postgres_keycloak
    restart: always
    ports: 
      - 5433:5432
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    image: jboss/keycloak
    restart: always
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres_keycloak
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      JAVA_OPTS: "-Dkeycloak.profile.feature.scripts=enabled
      -Dkeycloak.profile.feature.upload_scripts=enabled -server -Xms64m -Xmx512m 
      -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true 
      -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true"
    ports:
      - 8180:8080
    depends_on:
      - postgres_keycloak